### ISSUE TITLE
local install not working

### ISSUE THREAD

**Issue by manuel-delverme** [HearthSim/HSReplay.net#94]
```
➜  HSReplay.net git:(master) ✗ ./manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x7f4eef678c80>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named packs

```

**Comment by jleclanche** [comment]
You're using python 2.7 instead of 3.4+.

You should be using the vagrantfile anyway. Running `vagrant up` will set up and provision a production-ready server, and running `./scripts/run.sh` will start it.
