### ISSUE TITLE
Migration cards.0003_auto_20161008_1520 fails

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#96]
I cannot execute migration cards.0003_auto_20161008_1520 on a fresh database locally

```
==> default: Operations to perform:
==> default:   Apply all migrations: account, accounts, admin, api, auth, cards, contenttypes, django_comments, features, flatpages, games, packs, scenarios, sessions, sites, socialaccount, uploads
==> default: Running migrations:
==> default:   Applying cards.0003_auto_20161008_1520...
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
==> default:     return self.cursor.execute(sql)
==> default: psycopg2.ProgrammingError: syntax error at or near "ON"
==> default: LINE 30:   ) ON CONFLICT DO NOTHING;
==> default:              ^
==> default: 
==> default: 
==> default: The above exception was the direct cause of the following exception:
==> default: 
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/hsreplay.net/manage.py", line 11, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
==> default:     self.fetch_command(subcommand).run_from_argv(self.argv)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
==> default:     self.execute(*args, **cmd_options)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
==> default:     output = self.handle(*args, **options)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 204, in handle
==> default:     fake_initial=fake_initial,
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 115, in migrate
==> default:     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
==> default:     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
==> default:     state = migration.apply(state, schema_editor)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/db/migrations/migration.py", line 129, in apply
==> default:     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/db/migrations/operations/special.py", line 107, in database_forwards
==> default:     self._run_sql(schema_editor, self.sql)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/db/migrations/operations/special.py", line 132, in _run_sql
==> default:     schema_editor.execute(statement, params=None)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 112, in execute
==> default:     cursor.execute(sql, params)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
==> default:     return super(CursorDebugWrapper, self).execute(sql, params)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
==> default:     return self.cursor.execute(sql, params)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
==> default:     six.reraise(dj_exc_type, dj_exc_value, traceback)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
==> default:     raise value.with_traceback(tb)
==> default:   File "/home/vagrant/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
==> default:     return self.cursor.execute(sql)
==> default: django.db.utils.ProgrammingError: syntax error at or near "ON"
==> default: LINE 30:   ) ON CONFLICT DO NOTHING;
```

**Comment by beheh** [comment]
Can't reproduce after a reprovision, but I can't see any reason why my local database should have had this issue in the first place. What does the exception point to?

**Comment by jleclanche** [comment]
@beheh older vagrant boxes were using postgres 9.4 which is older than rds. I fixed it a few days ago.
