### ISSUE TITLE
Provisioning fails

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#97]
The following commands:

```
vagrant destroy
vagrant up
```

fail with the following output:

```
benedict@thundersnow ~/D/hsreplaynet (master)> vagrant destroy
    default: Are you sure you want to destroy the 'default' VM? [y/N] y
==> default: Destroying VM and associated drives...
benedict@thundersnow ~/D/hsreplaynet (master)> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'debian/contrib-jessie64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'debian/contrib-jessie64' is up to date...
==> default: Setting the name of the VM: hsreplaynet_default_1476961135012_50613
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8000 (guest) => 8000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.1
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /home/vagrant/hsreplay.net => /home/benedict/Dokumente/hsreplaynet
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20161020-7459-bj2k3d.sh
==> default: stdin: is not a tty
==> default: OK
==> default: OK
==> default: E: The method driver /usr/lib/apt/methods/https could not be found.
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following NEW packages will be installed:
==> default:   apt-transport-https
==> default: 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
==> default: Need to get 138 kB of archives.
==> default: After this operation, 195 kB of additional disk space will be used.
==> default: Get:1 http://httpredir.debian.org/debian/ jessie/main apt-transport-https amd64 1.0.9.8.3 [138 kB]
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Fetched 138 kB in 1s (98.4 kB/s)
==> default: Selecting previously unselected package apt-transport-https.
==> default: (Reading database ... 
==> default: (Reading database ... 5%
==> default: (Reading database ... 10%
==> default: (Reading database ... 15%
==> default: (Reading database ... 20%
==> default: (Reading database ... 25%
==> default: (Reading database ... 30%
==> default: (Reading database ... 35%
==> default: (Reading database ... 40%
==> default: (Reading database ... 45%
==> default: (Reading database ... 50%
==> default: (Reading database ... 55%
==> default: (Reading database ... 60%
==> default: (Reading database ... 65%
==> default: (Reading database ... 70%
==> default: (Reading database ... 75%
==> default: (Reading database ... 80%
==> default: (Reading database ... 85%
==> default: (Reading database ... 90%
==> default: (Reading database ... 95%
==> default: (Reading database ... 100%
==> default: (Reading database ... 
==> default: 40137 files and directories currently installed.)
==> default: Preparing to unpack .../apt-transport-https_1.0.9.8.3_amd64.deb ...
==> default: Unpacking apt-transport-https (1.0.9.8.3) ...
==> default: Setting up apt-transport-https (1.0.9.8.3) ...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E
==> default: : 
==> default: Unable to locate package influxdb
==> default: Reading package lists...
==> default: E: The value 'jessie-backports' is invalid for APT::Default-Release as such a release is not available in the sources
==> default: Reading package lists...
==> default: E: The value 'jessie-backports' is invalid for APT::Default-Release as such a release is not available in the sources
==> default: sed: can't read /etc/postgresql/9.5/main/pg_hba.conf: No such file or directory
==> default: Failed to restart postgresql.service: Unit postgresql.service failed to load: No such file or directory.
==> default: Failed to start influxdb.service: Unit influxdb.service failed to load: No such file or directory.
==> default: chsh: Warning: /bin/zsh does not exist
==> default: Password: 
==> default: chsh: PAM: Authentication failure
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20161020-7459-q315ws.sh
==> default: /tmp/vagrant-shell: line 11: python3: command not found
==> default: /tmp/vagrant-shell: line 12: /home/vagrant/env/bin/activate: No such file or directory
==> default: /tmp/vagrant-shell: line 13: pip: command not found
==> default: /tmp/vagrant-shell: line 14: pip: command not found
==> default: /tmp/vagrant-shell: line 17: nodeenv: command not found
==> default: /tmp/vagrant-shell: line 40: npm: command not found
==> default: /tmp/vagrant-shell: line 49: git: command not found
==> default: /tmp/vagrant-shell: line 52: createdb: command not found
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/hsreplay.net/manage.py", line 4, in <module>
==> default:     
==> default: from django.core.management import execute_from_command_line
==> default: ImportError
==> default: : 
==> default: No module named django.core.management
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/hsreplay.net/manage.py", line 4, in <module>
==> default:     
==> default: from django.core.management import execute_from_command_line
==> default: ImportError
==> default: : 
==> default: No module named django.core.management
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/hsreplay.net/scripts/initdb.py", line 13, in <module>
==> default:     
==> default: import django; django.setup()
==> default: ImportError
==> default: : 
==> default: No module named django
==> default: /tmp/vagrant-shell: line 57: influx: command not found
==> default: /tmp/vagrant-shell: line 58: influx: command not found
==> default: Updating /home/vagrant/hsreplay.net/scripts/../build/hsreplay-test-data
==> default: /home/vagrant/hsreplay.net/scripts/update_log_data.sh: line 23: git: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by beheh** [comment]
It seems to work with a *second* call to vagrant up, this time with --provision, so the following sequence of commands works:

```
vagrant destroy
vagrant up
vagrant up --provision
```

Why is this happening?
